= Maxina RPG
Kim Ravn Hansen <moccalotto@gmail.com>
:doctype: book
:toc:
:toclevels: 1
:sectnums:
:sectnumlevels: 1
:homepage: https://krhit.com/maxina

Welcome. This is the Maxina tabletop roleplaying game. It’s a pretty conventional tabletop rpg. We assume that you have prior knowledge of rpgs. If you haven’t, there are a myriad of free resources such as blogs, vlogs, podcasts, videos, etc you can consult to get you primed.

The game takes place in an alternate future where magic and cyberware exist side-by-side and technology, although advanced, can seem much more crude than the tech we use today. 

We’ve written a small primer on the world in the Maxina Campaign booklet. You do not need that booklet to play the game; we’ve written it to give you some fluff and inspiration, but you can make the game your own by inventing your own background history. 


== The character
Your character has a bunch of stats and stuff. We’ll go through all of them in this section.
Stats
Sometimes called attributes or ability scores in other systems, your stats are the core numbers that make up the foundation of your character. The human average score is 0. A new character's scores range from -2 to +4. 

Ballistics (BAL):: Your ability to use/shoot ranged and ballistics weapons such as pistols, rifles, throwing knives, and throwing grenades.
Melee (MEL):: Your close quarter combat ability. Including brawling and melee weapons.
Body (BOD):: Your health, stamina, strength, fortitude. 
Acrobatics (ACR):: Your ability to do acrobatic maneuvers. Dodging, balancing, certain martial arts moves, etc.
Essence (ESS):: Your ability to use magical abilities as well as your ability to power cyberware. 
Influence (INF):: Ability to sense motive, charm, intimidate, negotiate, etc.
Technomancy (TEC):: Your ability to use, manipulate, create, and repair technological devices. 
Senses (SEN):: Initiative, ability to spot and investigate hidden things.
Intelligence (INT):: Knowledge, logic, and deduction.

Assign the value _2d4-4_ to each stat. If you are not happy with the generated character, you can instead choose to assign the values  +4, +3, +2, +1, +1, 0, 0, -1, -1 to your stats in whichever order you want.

== Ancestry
Sometimes called races in other systems, your ancestry affects your stats and may grant you access to special perks. We will briefly go through the races here, but you can find more detailed information in the Maxina Campaign booklet.

include::./ancestries/original-human.asciidoc[]