= The Character

Your character has a bunch of stats and stuff. We’ll go through all of them in
this section.

All of the stuff that has to do with your character goes into this chapter. As
such there may be times where you may have to refer to the Playing The Game
chapter to get the whole picture. If you run into a term or word you don’t
understand, you can also refer to the Dictionary chapter, where we briefly
discuss all the technical terms of the game.

== Stats

Sometimes called attributes or ability scores in other systems, your stats are
the core numbers that make up the foundation of your character. The human
average score is 0. A new character's scores range from -2 to +4. 

Ballistics (BAL):: 
Your ability to use/shoot ranged and ballistics weapons such as pistols,
rifles, throwing knives, and throwing grenades.

Melee (MEL)::
Your close quarter combat ability. Including brawling and melee weapons.
Body (BOD)::
Your health, stamina, strength, fortitude. 
Acrobatics (ACR)::
Your ability to do acrobatic maneuvers. Dodging, balancing, certain martial
arts moves, etc.
Essence (ESS)::
Your ability to use magical abilities as well as your ability to power cyberware. 
Influence (INF)::
Ability to sense motive, charm, intimidate, negotiate, etc.
Technomancy (TEC)::
Your ability to use, manipulate, create, and repair technological devices.
Senses (SEN)::
Initiative, ability to spot and investigate hidden things.
Intelligence (INT)::
Knowledge, logic, and deduction.

Assign *2d4-4* to each stat. If you are not happy with the generated stats, you
can instead choose to assign the values  +4, +3, +2, +1, +1, 0, 0, -1, -1 to
your stats in whichever order you want.
